/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagamentoConfirmadoRouteImport } from './routes/pagamento-confirmado'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicKlivopayWebhookRouteImport } from './routes/api/public/klivopay-webhook'

const PagamentoConfirmadoRoute = PagamentoConfirmadoRouteImport.update({
  id: '/pagamento-confirmado',
  path: '/pagamento-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKlivopayWebhookRoute =
  ApiPublicKlivopayWebhookRouteImport.update({
    id: '/api/public/klivopay-webhook',
    path: '/api/public/klivopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento-confirmado': typeof PagamentoConfirmadoRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento-confirmado': typeof PagamentoConfirmadoRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento-confirmado': typeof PagamentoConfirmadoRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/pagamento-confirmado'
    | '/api/public/klivopay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/pagamento-confirmado'
    | '/api/public/klivopay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/pagamento-confirmado'
    | '/api/public/klivopay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  PagamentoConfirmadoRoute: typeof PagamentoConfirmadoRoute
  ApiPublicKlivopayWebhookRoute: typeof ApiPublicKlivopayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagamento-confirmado': {
      id: '/pagamento-confirmado'
      path: '/pagamento-confirmado'
      fullPath: '/pagamento-confirmado'
      preLoaderRoute: typeof PagamentoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/klivopay-webhook': {
      id: '/api/public/klivopay-webhook'
      path: '/api/public/klivopay-webhook'
      fullPath: '/api/public/klivopay-webhook'
      preLoaderRoute: typeof ApiPublicKlivopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  PagamentoConfirmadoRoute: PagamentoConfirmadoRoute,
  ApiPublicKlivopayWebhookRoute: ApiPublicKlivopayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
